### ISSUE TITLE
"All attacks completed" printed, but no result on target machine

### ISSUE THREAD

**Issue by kmanc** [insecurityofthings/jackit#18]
I'm trying to run the basic script that opens up notepad and writes "test complete" (instead of hello world or whatever the default is).  As far as I can tell things are working, because my terminal output says that it is finding the device, sending the attacks over the correct channel, and then says attacks are completed.  But when I check the target machine (a windows 7 box), notepad isn't open and I don't see signs that anything happened.  Any guesses as to what is going wrong?  Or steps I should take to troubleshoot?

**Comment by kmanc** [comment]
I'm just noticing that this was tested on Windows 8.1 and 10, is there a reason this would not work on Windows 7?  So far that is the only thing I see that could be the cause of my problem

**Comment by phikshun** [comment]
It should work with Windows 7. I've tested it with Windows 7 a few times since I wrote the README. I can think of a few reasons why it won't work. Perhaps you have this update installed? https://support.microsoft.com/en-us/kb/3152550
(I'm not sure if this fixes the issue -- I actually haven't tested the patch yet)

Also, we have noticed that some MS all-in-one devices don't seem to work... still trying to figure that one out too, since we can see them with the scanner.

What device are you trying to inject to?

**Comment by kmanc** [comment]
Hey thanks for getting back to me! I'm using a Logitech 260 keyboard (I don't know where the accompanying mouse is anymore) found here http://support.logitech.com/en_us/product/wireless-combo-mk260 . I can't remember if I installed the update either; I've had the keyboard for years so I suppose it is possible haha. 

Interesting that some all-in-ones don't work, but hey thanks for all of your efforts! 

----- Original Message -----

**Comment by kmanc** [comment]
Why exactly is this closed?  Feels like an open issue haha

**Comment by phikshun** [comment]
It's an exploit though... it's not supposed to work at all. There are a many variables that effect successful payload delivery and I can't account for them all.

If there's a specific bug that you'd like me to address, or if you have a pull request to submit, then I can re-open the issue.
