### ISSUE TITLE
No Module named lib

### ISSUE THREAD

**Issue by ankushgoel27** [insecurityofthings/jackit#34]
Hi,

Please see the error below. i followed your guide but this is the error i receive

$sudo jackit
Traceback (most recent call last):
  File "/usr/local/bin/jackit", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/jackit/bin/jackit", line 14, in <module>
    from jackit import mousejack
  File "/usr/local/lib/python2.7/dist-packages/jackit/mousejack.py", line 5, in <module>
    from jackit.lib import nrf24, nrf24_reset
ImportError: No module named lib

**Comment by Shiniyoukai** [comment]
From the howto; "You will also need to flash the firmware of the adapter using [Bastille's MouseJack research tools](https://github.com/RFStorm/mousejack)."

Have you followed the link and followed that guide?

**Comment by ankushgoel27** [comment]
yes,

I have already followed this guide. It used to work fine on your older version of jackit repo

**Comment by Sliim** [comment]
Look like you have multiple install of jackit (in `/opt/jackit` and `/usr/local/lib/python2.7/dist-packages/jackit`)
Try adding `/usr/local/lib/python2.7/dist-packages` to your `PYTHONPATH`

**Comment by elnerd** [comment]
I can confirm this problem on a fresh install of ubuntu. After doing 'python setup.py install', I see that the lib directory is missing from the /usr/local/lib/python2.7/dist-packages/jackit/ folder. I believe the problem is that 'jackit.lib' is not in the packages variable in setup.py.

Can someone with more knowledge of setup.py confirm this suspicion?

**Comment by elnerd** [comment]
Oh, I am not allowed to pull my own commit. Someone else has to do it.

**Comment by ankushgoel27** [comment]
its working fine now.
